# Generated by Django 4.2.1 on 2023-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField()),
                ('name', models.CharField()),
                ('age', models.CharField()),
                ('theme', models.CharField()),
            ],
        ),
    ]
